version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    hostname: api-service
    depends_on:
      - mongo_db
    networks:
      infranet:
        aliases:
        - 'api-service'
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
    hostname: mongodb-service
    networks:
      infranet:
        aliases:
        - 'mongodb-service'
  mongo_exporter:
    restart: 'always'
    ports:
      - '9216:9216'
    hostname: mongo-exporter
    image: "bitnami/mongodb-exporter"
    command:
      --mongodb.uri=mongodb://mongo_db:27017
      --compatible-mode
      --discovering-mode
    container_name: mongo-exporter-container
    # provide the mongodb service information for the exporter to work
    environment:
    - 'MONGO_SERVICE=mongo_db'
    - 'MONGO_PORT=27017'
    depends_on:
    - mongo_db
    networks:
      infranet:
        aliases:
        - 'mongodb-exporter-service'
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    hostname: prometheus
    networks:
      infranet:
        aliases:
        - 'prometheus-service'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    #volumes:
    #  - './grafana-config:/var/lib/grafana'
    hostname: grafana
    networks:
      infranet:
       aliases:
       - 'grafana-service'
networks:
  infranet:
